const en = {
    translation: {
        추가: `Add`,
        정상: `Normal`,
        비정상: `Abnormal`,
        '현재 알람 발생 내역이 없습니다.': `No alarms`,
        '***에 알람이 발생하였습니다.': `Alarm occured from ***`,
        '***을 포함한 **건에 알람이 발생하였습니다.': `** alarms occured including ***`,
        '로그아웃 되었습니다.': `You've been logged out`,
        사용자관리: `Manage Account`,
        제품등록: `Register Product`,
        기기관리: `Manage Device`,
        관제: `Control`,
        메인: `Main`,
        설정: `Setting`,
        로그아웃: `Logout`,
        출하증명서: `PoD`,
        발급불가: `Unable to issue`,
        정상발급: `Issued`,
        '발급 불가': `Unable to issue`,
        '정상 발급 완료': `Document issued`,
        '출하증명서 다운로드': `Download PoD`,
        알람: `Alarms`,
        '출하증명서 정상발급': `PoD issued`,
        배송중: `On the Way`,
        미사용: `Unused`,
        도착완료: `Delivered`,
        관리자M: `ADMIN M`,
        관리자: `ADMIN`,
        이용자: `USER`,
        출발: `Shipped `,
        검수: `On the Way`,
        도착: `Delivered`,
        '총 기기 수': `number of devices`,
        대: ``,
        '배송중 기기': `Devices on the way`,
        '도착 완료 기기': `Devices delivered`,
        '미사용 기기': `Unused device`,
        '내림차순으로 정렬': `Descending order`,
        '오름차순으로 정렬': `Ascending order`,
        '정렬 해제': `Revert to original sort order`,
        '데이터가 없습니다.': `There is no data`,
        출고지: `Place of shipment`,
        한국어: `Korean`,
        '언어 변경': `Change language`,
        '출력할 지도 정보가 없습니다.': `This page can't load Google Maps correctly`,
        '사용자가 추가되었습니다.': `User added`,
        '사용중인 이메일입니다.': `Email already in use`,
        '사용자 정보가 변경되었습니다.': `User information updated`,
        '회원정보 등록': `Register Account Information`,
        '회원정보 변경': `Edit Account Information`,
        이름: `Name`,
        '이름을 입력해주세요.': `Enter your name`,
        '필수 입력': `Required field`,
        등급: `Admin status`,
        '등급을 선택해주세요.': `Enter your admin status`,
        연락처: `Contact Number`,
        '연락처를 입력해주세요.': `Enter your contact number`,
        이메일: `Email`,
        '이메일을 입력해주세요.': `Enter your email`,
        등록: `Register`,
        변경: `Edit`,
        '출하증명서를 불러오는 중 문제가 발생했습니다.': `There was a problem in transferring the report`,
        '파일 추출이 시작되었습니다. 다운로드 내역을 확인하세요.': `File extraction in progress. Check the download history`,
        '파일 추출 중 문제가 발생했습니다.': `There was a problem in extracting the file`,
        다운로드: `Download`,
        '**개의 출하증명서 다운로드가 시작되었습니다.': `** PoD documents being downloaded`,
        '다시 다운로드': `Download again`,
        '정상발급 **개 다운로드': `** documents downloaded`,
        'S/N를 입력하세요.': `Enter S/N`,
        '제품이 등록되었습니다.': `Product registered`,
        '사용중인 S/N: ********이 포함되어 있습니다. 다시 확인하세요.': `S/N ******** in use. Please try again`,
        '제품이 수정되었습니다.': `Product information updated`,
        '제품 신규 등록': `Add a new product`,
        '제품 정보 변경': `Edit product information`,
        제품명: `Product name`,
        '제품명 입력': `Enter the product name`,
        'ex) 본사, 아산 1공장, F06 창고 등': `ex) HQ, Asan Plant 1, F06 warehouse, etc.`,
        '출고지 입력': `Enter the place of shipment`,
        '알람 설정': `Alarm settings`,
        '(범위를 입력하지 않으면 알람이 작동하지 않습니다.)': `(Alarms don't work unless the alarm range is entered)`,
        '온도 범위': `Temperature range`,
        '값 입력': `Enter the number`,
        '*** ~ ***(℃)의 범위를 벗어날 때 온도 알람이 발생합니다.': `Alarms occur when the temperature is out of range ***~*** (℃)`,
        '*** ~ ***(%)의 범위를 벗어날 때 습도 알람이 발생합니다.': `Alarms occur when the humidity is out of range *** ~ ***(%)`,
        '** (G)를 초과할 때 충격 알람이 발생합니다.': `Alarms occur when the shock is over **G`,
        '** G 이하': `Under **G`,
        '습도 범위': `Humidity range`,
        '충격 감지': `Shock detection`,
        '시리얼번호 입력은 필수입니다.': `Serial number is a required field`,
        'Serial No. 입력': `Enter Serial No.`,
        '1개 단위로 시리얼 번호를 등록할 수 있습니다.': `Serial numbers can be added one at a time`,
        '여러개의 시리얼 번호를 등록할 수 있습니다.': `Multiple serial numbers can be added`,
        '새 비밀번호와 비밀번호 확인이 일치하지 않습니다.': `Your confirmation password does not match the new password`,
        '새 비밀번호와 현재 비밀번호가 동일합니다.': `Your new password match the current password`,
        '비밀번호가 변경되었습니다. 개인정보를 위해 다시 로그인해주세요.': `Password updated. Please log in again`,
        '현재 비밀번호를 다시 입력해주세요.': `Please re-enter the current password`,
        '비밀번호 변경 중 문제가 발생했습니다.': `There was a problem in changing the password`,
        '회원 정보 수정': `Edit Account Information`,
        윌로그바이오: `Willog Bio`,
        '연락처 입력': `Enter the phone number`,
        회사명: `Company name`,
        '회사명 입력': `Enter the company name`,
        주소: `Address`,
        '주소 입력': `Enter the address`,
        '비밀번호 변경': `Change password`,
        '현재 비밀번호': `Current password`,
        '현재 비밀번호 입력': `Enter the current password`,
        '새 비밀번호': `New password`,
        '새 비밀번호 입력': `Enter the new password`,
        '새 비밀번호 확인': `Confirm the new password`,
        '새 비밀번호와 일치하지 않습니다.': `Your confirmation password does not match the new password`,
        저장: `Save`,
        제품: `Product`,
        추가하기: `Add`,
        출고: `Shipped`,
        건: ``,
        '정상 발급': `Issued`,
        '출하증명서 발급 불가': `Unable to issue PoD document`,
        '사이드메뉴 접기': `Fold the menu`,
        '사이드메뉴 펼치기': `Open the menu`,
        '배송 내역': `Shipment history`,
        상태: `Status`,
        '충격 범위(MAX)': `Shock range (MAX)`,
        등록일: `Registration date`,
        삭제: `Delete`,
        사용횟수: `Number of uses`,
        '운영 현황': `Current device status`,
        '최종 도착지': `Final destination`,
        '최종 업데이트일': `Last updated date`,
        '휴대폰 번호': `Phone number`,
        '사용자가 삭제되었습니다.': `User deleted`,
        '회원정보 삭제': `Delete account information`,
        취소: `Cancel`,
        '회원정보를 정말 삭제하시겠습니까?': `Do you wish to delete the account information?`,
        '이용자 정보를 입력하여 조회할 수 있습니다.': `Enter user information to view products`,
        '등록일을 입력하여 조회할 수 있습니다.': `Enter the registration date to view products`,
        '제품목록을 다운로드 할 수 있습니다.': `Product list can be downloaded`,
        '제품을 추가 할 수 있습니다.': `Additional products can be added`,
        '정상발급된 출하증명서를 1개 이상 선택하세요': `Select at least 1 PoD document `,
        '제품명을 입력하여 조회할 수 있습니다.': `Search the product by entering its name`,
        '출하증명서를 다운로드 할 수 있습니다.': `PoD reports can be downloaded`,
        '상세 정보': `More Information`,
        '저장 방법': `Storage Method`,
        '수송자 이름': `Carrier name`,
        '온·습도 그래프': `Temperature and humidity graph`,
        온도: `Temperature`,
        최고점: `Highest point`,
        최저점: `Lowest point`,
        '알람 범위': `Alarm range`,
        평균: `Average`,
        습도: `Humidity`,
        '기록 내역': `Record history`,
        '제품명 또는 S/N을 입력하여 조회할 수 있습니다.': `Access information by entering product name or S/N`,
        '알람이 발생했습니다.': `An alarm has occured`,
        '온도 알람': `Temperature alarm`,
        '배송 내역 (총 -개월 -일 -시간 -분)': `Shipment information ( m, h, d, m in total) `,
        '지도 보기': `View map`,
        더보기: `More information`,
        '발급 받으러 가기': `Issue document`,
        '제품이 삭제되었습니다.': `The product has been deleted`,
        '관리자 마스터만 삭제 할 수 있습니다.': `Deletion limited to authorized admins `,
        '제품 삭제': `Delete product`,
        '제품정보를 정말 삭제하시겠습니까?': `Do you really wish to delete the product information?`,
        '제품을 추가할 수 있습니다.': `Add new products`,
        '권한이 없는 계정입니다.': `The account is unauthorized`,
        '이메일 또는 비밀번호를 다시 확인하세요.': `Please check your email or password again`,
        '이메일을 입력하세요.': `Enter your email`,
        '비밀번호를 입력하세요.': `Enter your password`,
        비밀번호: `Password`,
        로그인: `Login`,
        '잘못된 접근입니다.': `Access denied`,
        충격: `Shock`,
        일시: `Date`,
        '언어가 변경되었습니다.': `Language changed`,
        '현재 기기 현황': `Current device status`,
        '올바른 범위의 값을 입력하세요.': `Enter the number within the specified range `,
        '사용자목록을 다운로드 할 수 있습니다.': `User list can be downloaded`,
        '사용자를 추가 할 수 있습니다.': `Additional users can be added`,
        '기기목록을 다운로드 할 수 있습니다.': `Device list can be downloaded`,
    },
};

export default en;
