export const ACCESS_TOKEN_EXPIRE = 'ACCESS_TOKEN_EXPIRE_EXCEPTION';
export const REFRESH_TOKEN_EXPIRE = 'REFRESH_TOKEN_EXPIRE_EXCEPTION';
export const INVALID_ACCOUNT = 'INVALID_CREDENTIAL_EXCEPTION';
export const INVALID_REFRESH_TOKEN = 'INVALID_REFRESH_TOKEN_EXCEPTION';
export const INVALID_ACCESS_TOKEN = 'INVALID_ACCESS_TOKEN_EXCEPTION';
